// src/screens/Home.tsx
import {
  IconCalendarEvent,
  IconPlayerPlay,
  IconSettings,
} from "@tabler/icons-react";
import { useTranslation } from "react-i18next";

import { Button, Screen } from "~src/components";
import { useRouterStore } from "~src/stores";

export function Home() {
  const { t } = useTranslation();

  const { navigate } = useRouterStore.use.actions();
  const navigateToSettings = () => navigate({ location: "settings" });

  return (
    <Screen>
      <h1>{t("menu.title")}</h1>
      <Button icon={IconPlayerPlay}>{t("menu.play")}</Button>
      <Button icon={IconCalendarEvent}>{t("menu.daily")}</Button>
      <Button icon={IconSettings} onClick={navigateToSettings}>
        {t("menu.settings")}
      </Button>
    </Screen>
  );
}

// src/views/Home.svelte
<script lang="ts">
  import { _ } from "svelte-i18n";
  import {
    IconCalendarEvent,
    IconPlayerPlay,
    IconSettings,
  } from "@tabler/icons-svelte";

  import { navigate } from "~stores/router-store";
  import Button from "~components/Button.svelte";
  import Screen from "~components/Screen.svelte";
</script>

<Screen>
  <h1>{$_("menu.title")}</h1>
  <Button on:click={() => navigate({ route: "play" })} icon={IconPlayerPlay}
    >{$_("menu.play")}</Button
  >
  <Button icon={IconCalendarEvent}>{$_("menu.daily")}</Button>
  <Button on:click={() => navigate({ route: "settings" })} icon={IconSettings}
    >{$_("menu.settings")}</Button
  >
</Screen>
