// src/views/level/Board.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";

  import { type Board } from "~src/levels";
  import { resetSelectedIndices } from "~src/stores/level-store";

  import Operation from "./Operation.svelte";
  import Node from "./Node.svelte";

  export let board: Board;
  const { boardSize } = board.difficulty;
  const { edges } = board;

  const handleMouseUp = () => {
    resetSelectedIndices();
  };

  onMount(() => document.addEventListener("mouseup", handleMouseUp));
  onDestroy(() => document.removeEventListener("mouseup", handleMouseUp));
</script>

<div class="nodes" style:--grid-size={boardSize}>
  {#each board.nodes.entries() as [i, node]}
    <Node value={node} index={i} {boardSize} />
  {/each}
  {#each edges.slice(0, edges.length / 2).entries() as [i, edge]}
    <div
      class="edge horizontal"
      style:--row={Math.floor(i / (boardSize - 1))}
      style:--column={i % (boardSize - 1)}
    >
      <Operation kind={edge.kind} />
    </div>
  {/each}
  {#each edges.slice(edges.length / 2).entries() as [i, edge]}
    <div
      class="edge vertical"
      style:--row={Math.floor(i / boardSize)}
      style:--column={i % boardSize}
    >
      <Operation kind={edge.kind} />
    </div>
  {/each}
</div>

<style lang="scss">
  .nodes {
    --node-size: var(--ui-size);
    --gap-size: calc(
      (var(--ui-width) - var(--grid-size) * var(--node-size)) /
        (var(--grid-size) - 1)
    );

    width: var(--ui-width);
    height: var(--ui-width);
    position: relative;

    .edge {
      position: absolute;
      display: flex;
      transform: translate(-50%, -50%);

      &.horizontal {
        top: calc(
          var(--node-size) / 2 + var(--row) *
            (var(--gap-size) + var(--node-size))
        );
        left: calc(
          var(--node-size) + (var(--gap-size) / 2) + var(--column) *
            (var(--gap-size) + var(--node-size))
        );
      }

      &.vertical {
        top: calc(
          var(--node-size) + (var(--gap-size) / 2) + var(--row) *
            (var(--gap-size) + var(--node-size))
        );
        left: calc(
          var(--node-size) / 2 + var(--column) *
            (var(--gap-size) + var(--node-size))
        );
      }
    }
  }
</style>

// src/features/Board/Board.tsx
import { IconDivide, IconMinus, IconPlus, IconX } from "@tabler/icons-react";
import { clsx } from "clsx";
import { useEffect } from "react";

import { useGeneratedLevel } from "~src/hooks";
import { type OperationKind } from "~src/levels";
import { useLevelStore } from "~src/stores";

import classes from "./Board.module.css";
import { Node } from "./Node";

const operationIcons: Record<OperationKind, JSX.Element> = {
  addition: <IconPlus size={16} />,
  subtraction: <IconMinus size={16} />,
  multiplication: <IconX size={16} />,
  division: <IconDivide size={16} />,
};

export function Board(): JSX.Element {
  const generatedLevel = useGeneratedLevel();
  const nodes = useLevelStore.use.nodes();
  const { resetSelectedNodes } = useLevelStore.use.actions();

  const { boardSize } = generatedLevel.board.difficulty;
  const { edges } = generatedLevel.board;

  useEffect(() => {
    const handleMouseUp = () => resetSelectedNodes();

    window.addEventListener("mouseup", handleMouseUp);
    return () => window.removeEventListener("mouseup", handleMouseUp);
  }, [resetSelectedNodes]);

  return (
    <div
      className={classes.board}
      style={
        {
          "--board-size": boardSize,
        } as React.CSSProperties
      }
    >
      {nodes.map((n) => (
        <Node node={n} key={n.id} />
      ))}
      {edges.map((edge, i) => {
        const isHorizontal = i < edges.length / 2;
        const boardSizeOffset = isHorizontal ? 1 : 0;
        const index = isHorizontal ? i : i - edges.length / 2;

        return (
          <div
            key={i}
            className={clsx(
              classes.edge,
              isHorizontal ? classes.horizontal : classes.vertical
            )}
            style={
              {
                "--row": Math.floor(index / (boardSize - boardSizeOffset)),
                "--column": index % (boardSize - boardSizeOffset),
              } as React.CSSProperties
            }
          >
            {operationIcons[edge.kind]}
          </div>
        );
      })}
    </div>
  );
}
